### ISSUE TITLE
SchedSTM Todo list

### ISSUE THREAD

**Issue by PunchShadow** [PunchShadow/TinySTMRocks#1]
Scheduler interface
- [ ] action.h
- [ ] scheduler_interface.h
- [ ] Makefile (runtime configuration flags)

Statistic data wrapping
- [ ] stat_args.h
  - [ ] verbose_stat_t definition 
  - [ ] GC on verbose_stat_t
- [ ] conflict_probability_table.h
- [ ] (integrate) scheduler_interface.h
- [ ] (integrate) tls.h

Execution data wrapping
- [ ] task_args.h
- [ ] conflict_tracking_table.h
- [ ] (integrate) scheduler_interface.h
- [ ] (integrate) tls.h
